=== Wh0l3/Lotto/bin/application/lottery_tickets.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema targetNamespace="http://www.leafit.ch/lottery_tickets/"
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.leafit.ch/lottery_tickets/">

      <element name="lottery_tickets" type="tns:LotteryTicketsType">
          <unique name="uniqueConstrIdent">
             <selector xpath="lottery_ticket/identifier" />
             <field xpath="." />
          </unique>
      </element>
      
      <element name="lottery_ticket" type="tns:LotteryTicketType"></element>

      <complexType name="LotteryTicketsType">
            <sequence>
                  <element name="lottery_ticket"
                  	type="tns:LotteryTicketType" maxOccurs="unbounded"
                  	minOccurs="1">
                  </element>
            </sequence>
      </complexType>

      <complexType name="PlayType">
            <sequence>
                  <element name="lottery_numbers"
                        type="tns:NumberDrawingType" maxOccurs="1" minOccurs="1">
                        <unique name="uniqueConstrLotteryNumber">
                              <selector xpath="lottery_number" />
                              <field xpath="." />
                        </unique>
                  </element>
                  <element name="star_numbers" type="tns:StarNumbersType" maxOccurs="1" minOccurs="1">
                        <unique name="uniqueConstrStarNumber">
                              <selector xpath="star_number" />
                              <field xpath="." />
                        </unique>
                  </element>
                  <element name="super_star_numbers" type="tns:SuperStarType" maxOccurs="1" minOccurs="1"> </element>
            </sequence>
      </complexType>
      
      <complexType name="NumberDrawingType">
      <sequence>
            <element name="lottery_number" type="tns:LotteryNumbersSelectionType" maxOccurs="5" minOccurs="5"> </element>
      </sequence>
    </complexType>

      <simpleType name="LotteryNumbersSelectionType">
            <restriction base="int">
                  <minInclusive value="1"></minInclusive>
                  <maxInclusive value="50"></maxInclusive>
            </restriction>
      </simpleType>

      <simpleType name="StarNumberSelectionType">
      <restriction base="int">
            <minInclusive value="1"></minInclusive>
            <maxInclusive value="11"></maxInclusive>
      </restriction>
    </simpleType>

    <simpleType name="SuperStarSelectionType">
      <restriction base="string"></restriction>
    </simpleType>

    <simpleType name="DrawingsSelectionType">
      <restriction base="int">
            <enumeration value="1"></enumeration>
            <enumeration value="2"></enumeration>
            <enumeration value="4"></enumeration>
            <enumeration value="6"></enumeration>
            <enumeration value="8"></enumeration>
            <enumeration value="10"></enumeration>
      </restriction>
    </simpleType>

    <complexType name="StartNumbersType">
      <sequence>
            <element name="star_number" type="tns:StarNumberSelectionType" maxOccurs="2" minOccurs="2"> </element>
      </sequence>
    </complexType>

    <complexType name="StarNumbersType">
      <sequence>
            <element name="star_number" type="tns:StarNumberSelectionType" maxOccurs="2" minOccurs="2"> </element>
      </sequence>
    </complexType>

    <complexType name="SuperStarType">
      <sequence>
            <element name="super_star" type="tns:SuperStarSelectionType" maxOccurs="4" minOccurs="1"></element>
      </sequence>
    </complexType>

    <complexType name="LotteryTicketType">
    	<sequence>
    		<element name="identifier" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="play" type="tns:PlayType" maxOccurs="7" minOccurs="1"> </element>
    		<element name="nbr_of_valid_drawings" type="tns:DrawingsSelectionType" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    	<attribute name="drawing_date" type="date"></attribute>
    </complexType>
</schema>

=== Wh0l3/Lotto/lottery_tickets2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:lottery_tickets xmlns:tns="http://www.leafit.ch/lottery_tickets/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.leafit.ch/lottery_tickets/ src/application/lottery_tickets.xsd ">
  <lottery_ticket drawing_date="2001-01-01">
    <identifier>0</identifier>
    <play>
      <lottery_numbers>
        <lottery_number>1</lottery_number>
        <lottery_number>2</lottery_number>
        <lottery_number>3</lottery_number>
        <lottery_number>4</lottery_number>
        <lottery_number>5</lottery_number>
      </lottery_numbers>
      <star_numbers>
        <star_number>10</star_number>
        <star_number>11</star_number>
      </star_numbers>
      <super_star_numbers>
        <super_star>super_star</super_star>
      </super_star_numbers>
    </play>
    <nbr_of_valid_drawings>1</nbr_of_valid_drawings>
  </lottery_ticket>
</tns:lottery_tickets>

=== Wh0l3/Lotto/src/application/lottery_tickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:lottery_ticket drawing_date="2001-01-01" xmlns:tns="http://www.leafit.ch/lottery_tickets/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.leafit.ch/lottery_tickets/ lottery_tickets.xsd ">
  <identifier>0</identifier>
  <play>
    <lottery_numbers>
      <lottery_number>0</lottery_number>
      <lottery_number>0</lottery_number>
      <lottery_number>0</lottery_number>
      <lottery_number>0</lottery_number>
      <lottery_number>0</lottery_number>
    </lottery_numbers>
    <star_numbers>
      <star_number>0</star_number>
      <star_number>0</star_number>
    </star_numbers>
    <super_star_numbers>
      <super_star>super_star</super_star>
    </super_star_numbers>
  </play>
  <nbr_of_valid_drawings>1</nbr_of_valid_drawings>
</tns:lottery_ticket>
